/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidarContaRouteImport } from './routes/validar-conta'
import { Route as ValidarRouteImport } from './routes/validar'
import { Route as TermoRouteImport } from './routes/termo'
import { Route as RetirarRouteImport } from './routes/retirar'
import { Route as RelatorioRouteImport } from './routes/relatorio'
import { Route as PermutacaoRouteImport } from './routes/permutacao'
import { Route as OcorrenciasRouteImport } from './routes/ocorrencias'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as DevolverRouteImport } from './routes/devolver'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'

const ValidarContaRoute = ValidarContaRouteImport.update({
  id: '/validar-conta',
  path: '/validar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidarRoute = ValidarRouteImport.update({
  id: '/validar',
  path: '/validar',
  getParentRoute: () => rootRouteImport,
} as any)
const TermoRoute = TermoRouteImport.update({
  id: '/termo',
  path: '/termo',
  getParentRoute: () => rootRouteImport,
} as any)
const RetirarRoute = RetirarRouteImport.update({
  id: '/retirar',
  path: '/retirar',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioRoute = RelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const PermutacaoRoute = PermutacaoRouteImport.update({
  id: '/permutacao',
  path: '/permutacao',
  getParentRoute: () => rootRouteImport,
} as any)
const OcorrenciasRoute = OcorrenciasRouteImport.update({
  id: '/ocorrencias',
  path: '/ocorrencias',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const DevolverRoute = DevolverRouteImport.update({
  id: '/devolver',
  path: '/devolver',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/checklist': typeof ChecklistRoute
  '/dashboard': typeof DashboardRoute
  '/devolver': typeof DevolverRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/ocorrencias': typeof OcorrenciasRoute
  '/permutacao': typeof PermutacaoRoute
  '/relatorio': typeof RelatorioRoute
  '/retirar': typeof RetirarRoute
  '/termo': typeof TermoRoute
  '/validar': typeof ValidarRoute
  '/validar-conta': typeof ValidarContaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/checklist': typeof ChecklistRoute
  '/dashboard': typeof DashboardRoute
  '/devolver': typeof DevolverRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/ocorrencias': typeof OcorrenciasRoute
  '/permutacao': typeof PermutacaoRoute
  '/relatorio': typeof RelatorioRoute
  '/retirar': typeof RetirarRoute
  '/termo': typeof TermoRoute
  '/validar': typeof ValidarRoute
  '/validar-conta': typeof ValidarContaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/checklist': typeof ChecklistRoute
  '/dashboard': typeof DashboardRoute
  '/devolver': typeof DevolverRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/ocorrencias': typeof OcorrenciasRoute
  '/permutacao': typeof PermutacaoRoute
  '/relatorio': typeof RelatorioRoute
  '/retirar': typeof RetirarRoute
  '/termo': typeof TermoRoute
  '/validar': typeof ValidarRoute
  '/validar-conta': typeof ValidarContaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/checklist'
    | '/dashboard'
    | '/devolver'
    | '/inventario'
    | '/login'
    | '/ocorrencias'
    | '/permutacao'
    | '/relatorio'
    | '/retirar'
    | '/termo'
    | '/validar'
    | '/validar-conta'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/checklist'
    | '/dashboard'
    | '/devolver'
    | '/inventario'
    | '/login'
    | '/ocorrencias'
    | '/permutacao'
    | '/relatorio'
    | '/retirar'
    | '/termo'
    | '/validar'
    | '/validar-conta'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/checklist'
    | '/dashboard'
    | '/devolver'
    | '/inventario'
    | '/login'
    | '/ocorrencias'
    | '/permutacao'
    | '/relatorio'
    | '/retirar'
    | '/termo'
    | '/validar'
    | '/validar-conta'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  ChecklistRoute: typeof ChecklistRoute
  DashboardRoute: typeof DashboardRoute
  DevolverRoute: typeof DevolverRoute
  InventarioRoute: typeof InventarioRoute
  LoginRoute: typeof LoginRoute
  OcorrenciasRoute: typeof OcorrenciasRoute
  PermutacaoRoute: typeof PermutacaoRoute
  RelatorioRoute: typeof RelatorioRoute
  RetirarRoute: typeof RetirarRoute
  TermoRoute: typeof TermoRoute
  ValidarRoute: typeof ValidarRoute
  ValidarContaRoute: typeof ValidarContaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validar-conta': {
      id: '/validar-conta'
      path: '/validar-conta'
      fullPath: '/validar-conta'
      preLoaderRoute: typeof ValidarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validar': {
      id: '/validar'
      path: '/validar'
      fullPath: '/validar'
      preLoaderRoute: typeof ValidarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termo': {
      id: '/termo'
      path: '/termo'
      fullPath: '/termo'
      preLoaderRoute: typeof TermoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retirar': {
      id: '/retirar'
      path: '/retirar'
      fullPath: '/retirar'
      preLoaderRoute: typeof RetirarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio': {
      id: '/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof RelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permutacao': {
      id: '/permutacao'
      path: '/permutacao'
      fullPath: '/permutacao'
      preLoaderRoute: typeof PermutacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocorrencias': {
      id: '/ocorrencias'
      path: '/ocorrencias'
      fullPath: '/ocorrencias'
      preLoaderRoute: typeof OcorrenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devolver': {
      id: '/devolver'
      path: '/devolver'
      fullPath: '/devolver'
      preLoaderRoute: typeof DevolverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  ChecklistRoute: ChecklistRoute,
  DashboardRoute: DashboardRoute,
  DevolverRoute: DevolverRoute,
  InventarioRoute: InventarioRoute,
  LoginRoute: LoginRoute,
  OcorrenciasRoute: OcorrenciasRoute,
  PermutacaoRoute: PermutacaoRoute,
  RelatorioRoute: RelatorioRoute,
  RetirarRoute: RetirarRoute,
  TermoRoute: TermoRoute,
  ValidarRoute: ValidarRoute,
  ValidarContaRoute: ValidarContaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
